---
bind_acls:
  - name: "ns1"
    match_list:
      - "10.10.0.3"
      - "fd36:3eb3:43b0:a::3"
  - name: "ns2"
    match_list:
      - "10.10.0.4"
      - "fd36:3eb3:43b0:a::4"
bind_allow_query:
  - "any"
bind_listen_ipv4:
  - "any"
bind_listen_ipv6:
  - "any"
bind_zones:
  - name: "tswn.us"
    create_reverse_zones: true
    primaries: 
      - "fd36:3eb3:43b0:a::3"
    name_servers:
      - "shadowofsunderedstar.hogs.tswn.us."
      - "bornstellarmakeseternallasting.hogs.tswn.us."
    hosts:
      - name: "maccabeus.hogs"
        ip: "10.117.0.1"
        ipv6: "fd36:3eb3:43b0:75::1"
        aliases:
          - "home"
      - name: "mysql.hogs"
        ip: "10.117.0.5"
        ipv6: "fd36:3eb3:43b0:75::5"
      - name: "nut.hogs"
        ip: "10.117.0.9"
        ipv6: "fd36:3eb3:43b0:75::9"
      - name: "firstlightweaveslivingsong.hogs"
        ip: "10.117.0.10"
        ipv6: "fd36:3eb3:43b0:75::a"
      - name: "dadab.hogs"
        ip: "10.117.0.11"
        ipv6: "fd36:3eb3:43b0:75::b"
      - name: "palamok.hogs"
        ip: "10.117.0.12"
        ipv6: "fd36:3eb3:43b0:75::c"
        aliases:
          - "mqtt.hogs"
      - name: "nvidia-shield.hogs"
        ip: "10.117.0.13"
        ipv6: "fd36:3eb3:43b0:75:864:f450:825c:a847"
      - name: "sif.hogs"
        ip: "10.117.0.16"
        ipv6: "fd36:3eb3:43b0:75::10"
        aliases:
          - "zwave.hogs"
      - name: "harvest.hogs"
        ip: "10.117.0.17"
        ipv6: "fd36:3eb3:43b0:75::11"
        aliases:
          - "opensprinkler.hogs"
      - name: "cortana.hogs"
        ip: "10.117.0.19"
        ipv6: "fd36:3eb3:43b0:75::13"
        aliases:
          - "homeassistant.hogs"
      - name: "enduringbias.hogs"
        ip: "10.117.0.26"
        ipv6: "fd36:3eb3:43b0:75::1a"
        aliases:
          - "smokeping.hogs"
      - name: "iona.hogs"
        ip: "10.117.0.27"
        ipv6: "fd36:3eb3:43b0:75::1b"
        aliases:
          - "blueiris.hogs"
      - name: "docker-ssd.hogs"
        ip: "10.117.0.30"
        ipv6: "fd36:3eb3:43b0:75::1e"
        aliases:
          - "ara.hogs"
          - "factorio"
          - "valheim"
          - "valheim.hogs"
      - name: "zabbix-server.hogs"
        ip: "10.117.0.32"
        ipv6: "fd36:3eb3:43b0:75::20"
      - name: "zabbix.hogs"
        ip: "10.117.0.33"
        ipv6: "fd36:3eb3:43b0:75::21"
      - name: "maccabeus01.hogs"
        ip: "10.117.0.48"
        ipv6: "fd36:3eb3:43b0:75::30"
      - name: "maccabeus02.hogs"
        ip: "10.117.0.49"
        ipv6: "fd36:3eb3:43b0:75::31"
      - name: "0.ntp.hogs"
        ip: "10.117.0.50"
        aliases:
          - "pool.ntp.hogs"

      - name: "al-cygni.hogs"
        ip: "10.10.0.2"
        ipv6: "fd36:3eb3:43b0:a::2"
      - name: "shadowofsunderedstar.hogs"
        ip: "10.10.0.3"
        ipv6: "fd36:3eb3:43b0:a::3"
        aliases:
          - "ns1"
      - name: "bornstellarmakeseternallasting.hogs"
        ip: "10.10.0.4"
        ipv6: "fd36:3eb3:43b0:a::4"
        aliases:
          - "ns2"
      - name: "ups01.hogs"
        ip: "10.10.0.5"
        ipv6: "fd36:3eb3:43b0:a::5"
      - name: "docker-vm.hogs"
        ip: "10.10.0.6"
        ipv6: "fd36:3eb3:43b0:a::6"
      - name: "ipmi.firstlightweaveslivingsong.hogs"
        ip: "10.10.0.10"
        ipv6: "fd36:3eb3:43b0:a::a"
      - name: "ipmi.dadab.hogs"
        ip: "10.10.0.11"
        ipv6: "fd36:3eb3:43b0:a::b"
      - name: "sdwilsh-dev.hogs"
        ip: "10.10.0.20"
        ipv6: "fd36:3eb3:43b0:a::14"
      # Services
      - name: "installation02"
        ip: "10.82.0.2"
        aliases:
          - "unifi"
          - "unifi.hogs"
    networks:
      - "10.10.0"
      - "10.117.0"
    ipv6_networks:
      - "fd36:3eb3:43b0:a::/64"
      - "fd36:3eb3:43b0:75::/64"
