---
# tasks file for docker-zabbix-backend
- name: "Launch zabbix backend containers"
  community.docker.docker_compose:
    project_name: "zabbix_backend"
    definition:
      networks:
        man:
          external:
            name: "man"
      services:
        server:
          dns:
            - "10.10.0.1"
            - "fd36:3eb3:43b0:a::1"
          environment:
            DB_SERVER_HOST: "mysql.hogs.tswn.us"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: "{{ hostvars['mysql.hogs.tswn.us'].mysql_server__users | selectattr('name', 'equalto', 'zabbix') | map(attribute='password') | first }}"
            ZBX_ENABLE_SNMP_TRAPS: "true"
          image: "zabbix/zabbix-server-mysql:alpine-5.4-latest"
          mac_address: "02:42:0a:75:00:20"
          networks:
            man:
              ipv4_address: "10.10.0.18"
              ipv6_address: "fd36:3eb3:43b0:a::12"
              # This also gets an ipv6 address of fd36:3eb3:43b0:a:42:aff:fe75:20, based on the mac address.
          ports:
            - "10051:10051"
          stop_grace_period: "30s"
          volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "/home/zabbix/mibs:/var/lib/zabbix/mibs:ro"
            - "snmptraps:/var/lib/zabbix/snmptraps:rw"
        snmptraps:
          dns:
            - "10.10.0.1"
            - "fd36:3eb3:43b0:a::1"
          image: "zabbix/zabbix-snmptraps:alpine-5.4-latest"
          mac_address: "02:42:0a:75:00:21"
          networks:
            man:
              ipv4_address: "10.10.0.19"
              ipv6_address: "fd36:3eb3:43b0:a::13"
          ports:
            - "162:162/udp"
          stop_grace_period: "5s"
          volumes:
            - "/home/zabbix/mibs:/var/lib/zabbix/mibs:ro"
            - "snmptraps:/var/lib/zabbix/snmptraps:rw"
      volumes:
        snmptraps:
    pull: yes
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  register: status
- ansible.builtin.assert:
    that:
      - "status.services.server.zabbix_backend_server_1.state.running"
      - "status.services.snmptraps.zabbix_backend_snmptraps_1.state.running"
