---
- hosts: docker_ssd
  become: true
  roles:
    - role: common
    - role: ansible-cron
    - role: nickjj.docker
      tags: ["docker"]
    - role: ara-docker
    - role: factorio
    - role: valheim
      tags:
        - "valheim"
