---
- hosts: "all:!vyos"
  become: yes
  roles:
    - role: "common"
    - role: "ansible-cron"
    - role: "devsec.hardening.ssh_hardening"
      vars:
        ssh_kerberos_supprt: no
        ssh_listen_to: "{{ common__ip_addresses | ansible.netcommon.ipaddr('address') }}"
- import_playbook: "docker-ssd-host.yml"
- import_playbook: "dns.yml"
- import_playbook: "loki.hogs.tswn.us.yml"
- import_playbook: "mysql.yml"
- import_playbook: "opensprinkler.yml"
