---
- hosts: "all:!vyos"
  become: yes
  roles:
    - role: "common"
    - role: "ansible-cron"
    - role: "devsec.hardening.ssh_hardening"
      vars:
        ssh_kerberos_supprt: no
        ssh_listen_to: "{{ common__ip_addresses | ansible.netcommon.ipaddr('address') }}"
      when:
        - ansible_version.full is version("2.9.10", ">=")
- import_playbook: "plays/groups/dns.yml"
- import_playbook: "plays/hosts/docker-ssd.hogs.tswn.us.yml"
- import_playbook: "plays/hosts/docker-vm-public.hogs.tswn.us.yml"
- import_playbook: "plays/hosts/docker-vm.hogs.tswn.us.yml"
- import_playbook: "plays/hosts/harvest.hogs.tswn.us.yml"
- import_playbook: "plays/hosts/loki.hogs.tswn.us.yml"
- import_playbook: "plays/hosts/mysql.hogs.tswn.us.yml"
