---
- hosts: viseron
  become: true
  roles:
    - role: common
    - role: github-client
    - role: ansible-cron
    - role: nickjj.docker
      tags: ["docker"]
      vars:
        docker__state: "latest"
    - role: viseron