---
# defaults file for common
common__additional_ethernet_interfaces: []

# Dictonary of bonds.  For example:
# common__ethernet_interface_bonds:
#   bond0:
#     interfaces:
#       - eth0
#       - eth1

common__ethernet_interface_bonds: {}

# Interface name of the primary interface of the device.  This falls back to
# ansible_default_ipv4.interface if falsey.
common__ethernet_primary_interface: ""

common__etc_dir: "/etc"

common__ntp_pool: "pool.ntp.hogs.tswn.us"

common__unix_groups:
  - name: "ansible"
    gid: 2000
    sudo: true
  - name: "zabbix"
    gid: 2001
  - name: "srcs"
    gid: 2050
common__unix_users:
  - name: "ansible"
    uid: 2000
  - name: "zabbix"
    uid: 2001
