---
# tasks file for viseron
- name: Create viseron group
  group:
    name: viseron
    state: present
- name: Create viseron user
  user:
    name: viseron
    group: viseron
    groups:
      - docker
      - srcs
      - viseron
    state: present
    shell: /bin/bash
- name: Checkout viseron config
  git:
    repo: https://github.com/sdwilsh/viseron-config.git
    dest: /src/viseron-config
  become: yes
  become_user: viseron
- name: Create viseron secrets.yaml
  template:
    src: viseron_secrets.j2
    dest: /src/viseron-config/secrets.yaml
    owner: viseron
    group: viseron
    mode: 0640
# TODO: recordings directory
- name: Launch viseron container
  community.general.docker_compose:
    project_name: viseron
    definition:
      version: "2"
      services:
        viseron:
          image: roflcoopter/viseron:latest
          volumes:
            - "/src/viseron-config:/config"
            - "/home/viseron/recordings:/recordings"
            - "/etc/localtime:/etc/localtime:ro"
    pull: yes
  become: yes
  become_user: viseron
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
- assert:
    that:
      - "viseron.viseron_viseron_1.state.running"