---
- description: "Allow ICMP"
  action: "accept"
  protocol: "icmp"
  icmp:
    type_name: any
- action: "accept"
  protocol: "tcp"
  destination:
    group:
      address_group: "LUXOR-v4"
    port: "80"
- action: "accept"
  protocol: "tcp"
  destination:
    group:
      address_group: "OPENSPRINKLER-v4"
    port: "8080"
