---
- description: "Allow ICMP"
  action: "accept"
  protocol: "icmpv6"
- description: "Allow NTP"
  action: "accept"
  state:
    new: true
  destination:
    group:
      address_group: "NTP-SERVICES-v6"
      port_group: "NTP"
- description: "Allow ARA Connections"
  action: "accept"
  protocol: "tcp"
  state:
    new: true
  destination:
    address: "fd36:3eb3:43b0:75::1e"
    port: "8000"
- description: "Allow Zabbix Server Connections"
  action: "accept"
  protocol: "tcp"
  state:
    new: true
  destination:
    port: "10050"
  source:
    group:
      address_group: "ZABBIX-SERVER-v6"
- description: "Allow Zabbix Server Connections to MySQL"
  action: "accept"
  protocol: "tcp"
  state:
    new: true
  destination:
    group:
      address_group: "MYSQL-SERVER-v6"
    port: "3306"
  source:
    group:
      address_group: "ZABBIX-SERVER-v6"
- description: "Allow Connections to NFS"
  action: "accept"
  protocol: "tcp_udp"
  state:
    new: true
  destination:
    group:
      address_group: "FILE-SERVER-v6"
      port_group: "NFS"
