---
# defaults file for factorio

# Name of the game as it will appear in the game listing.
factorio__server_name: ""
# Description of the game that will appear in the listing.
factorio__server_description: ""
# Game tags.
factorio__server_tags: []

# If true, the game will be published on the official Factorio matching server.
factorio__server_visibility_public: True
# If true, the game will be broadcast on LAN.
factorio__server_visibility_lan: True

# Your factorio.com login credentials.  This is required for mods and games with public visibility.
factorio__username: ""
factorio__token: ""

factorio__game_password: ""

# List of mods.  Use name and enabled to list them out, i.e.:
# factorio__mods:
#   - name: "base"
#     enabled: True
factorio__mods: []