---
# tasks file for common-rpi
- name: "Install linux-modules-extra-raspi"
  ansible.builtin.apt:
    name: "linux-modules-extra-raspi"
    state: "present"

- include: "config.yml"
- include: "cm4io-fan.yml"
  when: common_rpi__cm4io_fan != None
