---
- hosts: "docker-vm.hogs.tswn.us"
  become: yes
  roles:
    - role: "docker-deepstack"
      tags:
        - "docker"
        - "deepstack"
    - role: "docker-viseron"
      tags:
        - "docker"
        - "viseron"
    - role: "docker-zabbix-backend"
      tags:
        - "docker"
        - "zabbix"
    - role: "docker-zabbix-frontend"
      tags:
        - "docker"
        - "zabbix"
