---
- hosts: "docker-ssd.hogs.tswn.us"
  become: true
  roles:
    - role: nickjj.docker
      tags: ["docker"]
    - role: ara-docker
    - role: factorio
    - role: valheim
      tags:
        - "valheim"
