---
- hosts: "docker_vm"
  become: yes
  roles:
    - role: "docker-zabbix-backend"
      tags:
        - "docker"
        - "zabbix"
    - role: "docker-zabbix-frontend"
      tags:
        - "docker"
        - "zabbix"
