---
# handlers file for common
- name: netplan apply
  ansible.builtin.command:
    argv:
      - "netplan"
      - "apply"

- name: "restart systemd-resolved"
  ansible.builtin.systemd:
    name: "systemd-resolved"
    state: "restarted"

- name: "restart zabbix-agent"
  ansible.builtin.systemd:
    name: "zabbix-agent"
    state: "restarted"
