---
- action: "accept"
  protocol: "vrrp"
  source:
    group:
      address_group: "PEER-v4"
- description: "Allow dhcp-sync"
  action: "accept"
  protocol: "tcp"
  destination:
    port: "520"
  source:
    group:
      address_group: "PEER-v4"
- description: "Allow ICMP"
  action: "accept"
  protocol: "icmp"
  icmp:
    type_name: any
- description: "Allow DHCP"
  action: "accept"
  protocol: "udp"
  source:
    port: "68"
  destination:
    port: "67"
- description: "Allow DNS"
  action: "accept"
  protocol: "tcp_udp"
  state:
    new: true
  destination:
    group:
      port_group: "DNS"
- description: "Allow SSH"
  action: "accept"
  destination:
    port: "22"
  protocol: "tcp"
  state:
    new: true
- description: "Drop Eaton Alarms Broadcast"
  action: "drop"
  protocol: "udp"
  destination:
    address: "255.255.255.255"
    port: "4680"
- description: "Allow Zabbix SNMP Connections"
  action: "accept"
  protocol: "tcp_udp"
  state:
    new: true
  destination:
    port: "161"
  source:
    group:
      address_group: "ZABBIX-SERVER-v4"
