---
# tasks file for vyos-firewall to load zone information.
- name: "Build rule_sets_{{ _afi }} for {{ zone.name }}"
  ansible.builtin.set_fact: >-
    rule_sets_{{ _afi }}={{
      lookup("vars", "rule_sets_" + _afi) + [
        dict(
          name=(zone.firewall_name | upper + "-from-" + file_path.split("/")[-1][5:-9] | upper + "-v" + _afi[-1]),
          description=ansible_managed,
          enable_default_log=True,
          default_action="drop",
          rules=lookup("template", "templates/firewall_rules.j2") | from_yaml,
        )
      ]
    }}
  with_fileglob: "{{ vyos_firewall__zones_path }}/{{ zone.firewall_name | lower }}/from-*-{{ _afi }}.yml"
  loop_control:
    loop_var: "file_path"
  tags:
    - "firewall-rules"
    - "firewall-zones"
  when:
    # Only run when we expect a zone to be paired with the zone we are building the ruleset for.
    - "file_path.split('/')[-1][5:-9].upper() in zone.from | map(attribute='firewall_name')"
