---
# tasks file for vyos-firewall
- name: "Load Firewall Zone Information for IPv4"
  ansible.builtin.include_tasks: "load_zone_info.yml"
  loop: "{{ vyos_firewall__zones }}"
  loop_control:
    loop_var: zone
  vars:
    afi: "ipv4"
- name: "Load Firewall Zone Information for IPv6"
  ansible.builtin.include_tasks: "load_zone_info.yml"
  loop: "{{ vyos_firewall__zones }}"
  loop_control:
    loop_var: zone
  vars:
    afi: "ipv6"
- name: "Set the firewall rules"
  vyos.vyos.vyos_firewall_rules:
    config:
      - afi: "ipv4"
        rule_sets: "{{ rule_sets_ipv4 | default([]) }}"
      - afi: "ipv6"
        rule_sets: "{{ rule_sets_ipv6 | default([]) }}"
    state: "replaced"
  # vars:
  #   ansible_persistent_log_messages: True
