---
# tasks file for vyos-firewall
- name: "Set default attribute values on vyos_firewall__zones"
  ansible.builtin.set_fact:
    vyos_firewall__zones: "{{ lookup('template', 'templates/vyos_firewall__zones.j2') | from_yaml }}"
- name: "Load Firewall Zone Information for IPv4"
  ansible.builtin.include_tasks: "load_zone_info.yml"
  loop: "{{ _named_firewalls }}"
  loop_control:
    loop_var: zone
  vars:
    _afi: "ipv4"
    _named_firewalls: "{{ vyos_firewall__zones | map(attribute='firewall_name') | unique | sort }}"
- name: "Load Firewall Zone Information for IPv6"
  ansible.builtin.include_tasks: "load_zone_info.yml"
  loop: "{{ _named_firewalls }}"
  loop_control:
    loop_var: zone
  vars:
    _afi: "ipv6"
    _named_firewalls: "{{ vyos_firewall__zones | map(attribute='firewall_name') | unique | sort }}"
- name: "Set the firewall rules"
  vyos.vyos.vyos_firewall_rules:
    config:
      - afi: "ipv4"
        rule_sets: "{{ rule_sets_ipv4 | default([]) }}"
      - afi: "ipv6"
        rule_sets: "{{ rule_sets_ipv6 | default([]) }}"
    state: "replaced"
  tags:
    - "firewall-rules"
- name: "Set Zone Policy"
  vyos.vyos.vyos_config:
    src: "zone-policy.j2"
