---
# tasks file for vyos-firewall
- name: "Set default attribute values on vyos_firewall__zones"
  ansible.builtin.set_fact:
    vyos_firewall__zones: "{{ lookup('template', 'templates/vyos_firewall__zones.j2') | from_yaml }}"
  tags:
    - "firewall-rules"
    - "firewall-zones"
- name: "Setup private helper variables"
  ansible.builtin.set_fact:
    _zone_name_info: "{{ lookup('template', 'templates/_zone_name_info.j2') | from_yaml }}"
  tags:
    - "firewall-rules"
    - "firewall-zones"
- name: "Load Firewall Zone Information for IPv4"
  ansible.builtin.include_tasks: "load_zone_info.yml"
  loop: "{{ _zone_name_info }}"
  loop_control:
    loop_var: zone
  tags:
    - "firewall-rules"
  vars:
    _afi: "ipv4"
- name: "Load Firewall Zone Information for IPv6"
  ansible.builtin.include_tasks: "load_zone_info.yml"
  loop: "{{ _zone_name_info }}"
  loop_control:
    loop_var: zone
  tags:
    - "firewall-rules"
  vars:
    _afi: "ipv6"
- name: "Set the firewall rules"
  vyos.vyos.vyos_firewall_rules:
    config:
      - afi: "ipv4"
        rule_sets: "{{ rule_sets_ipv4 | default([]) }}"
      - afi: "ipv6"
        rule_sets: "{{ rule_sets_ipv6 | default([]) }}"
    state: "replaced"
  tags:
    - "firewall-rules"
- name: "Set Zone Policy"
  vyos.vyos.vyos_config:
    src: "zone-policy.j2"
  tags:
    - "firewall-zones"
