---
# tasks file for installing custom facts for the common role
- name: "Create custom facts directory"
  ansible.builtin.file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Add custom facts"
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/ansible/facts.d/{{ item }}"
    mode: "u=rx,g=rx,o=rx"
  loop:
    - "jail.fact"
    - "rpi.fact"
  register: added_custom_fact

- name: Re-run setup to use custom facts
  setup: ~
  when: added_custom_fact.changed
