---
# Ports
- name: "Ensure /usr/local/etc/pkg/repos exists"
  ansible.builtin.file:
    path: "/usr/local/etc/pkg/repos"
    state: "directory"
    owner: "root"
    group: "wheel"
    mode: "u=rw,g=r,o=r"
  tags:
    - "pkg"
- name: "Use latest package builds"
  ansible.builtin.copy:
    dest: "/usr/local/etc/pkg/repos/FreeBSD.conf"
    content: |
      FreeBSD: {
        url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"
      }
    owner: "root"
    group: "wheel"
    mode: "u=rw,g=r,o=r"
  tags:
    - "pkg"

# Dependencies
- name: "Install latest version of Python"
  ansible.builtin.package:
    name: "python37"
    state: "present"
- name: "Symlink python37 to python3"
  ansible.builtin.file:
    src: "/usr/local/bin/python3.7"
    dest: "/usr/local/bin/python3"
    owner: "root"
    group: "wheel"
    mode: "o=rwx,g=rx,o=rx"
    state: "link"
- name: "Install latest version of sudo"
  ansible.builtin.package:
    name: "sudo"
    state: "present"
- name: "Install latest version of pip"
  ansible.builtin.package:
    name: "py37-pip"
    state: "present"
- name: "Symlink pip to pip3"
  ansible.builtin.file:
    src: "/usr/local/bin/pip-3.7"
    dest: "/usr/local/bin/pip3"
    owner: "root"
    group: "wheel"
    mode: "o=rwx,g=rx,o=rx"
    state: "link"

# Networking
- name: "Set hostname"
  ansible.builtin.copy:
    content: |
      {{ ansible_managed }}
      hostname={{ inventory_hostname }}
    dest: "/etc/rc.conf.d/hostname"
    mode: "u=rw,g=r,o=r"
    owner: "root"
    group: "wheel"
  tags:
    - "networking"
