---
- name: Create base unix groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  loop: "{{ common__unix_groups }}"
- name: Create base users
  user:
    group: "{{ item.name }}"
    name: "{{ item.name }}"
    shell: "/bin/bash"
    state: present
    uid: "{{ item.uid }}"
  loop: "{{ common__unix_users }}"
  when: ansible_distribution != "FreeBSD"
- name: Create base users (FreeBSD)
  user:
    group: "{{ item.name }}"
    name: "{{ item.name }}"
    shell: "/usr/local/bin/bash"
    state: present
    uid: "{{ item.uid }}"
  loop: "{{ common__unix_users }}"
  when: ansible_distribution == "FreeBSD"
- name: Deploy ansible user's public key
  authorized_key:
    user: ansible
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMiRn+dJyIkJ22qrkuMlNC33xxS7VUwkYRY/55Wf4ryq"
- name: Setup sudoers
  template:
    src: sudoers.j2
    dest: "{{ common__etc_dir + '/sudoers.d/ansible' }}"
    validate: 'visudo -cf %s'
    mode: 0440

- include: facts.yml
- include: iscsi.yml

# Platform-specific stuff
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

# Cleanup From Provisioning
- name: Remove provision user
  user:
    name: provision
    state: absent
  when: ansible_user_id != "provision" and ansible_env.SUDO_USER != "provision"
- name: Remove provision group
  group:
    name: provision
    state: absent
  when: ansible_user_id != "provision" and ansible_env.SUDO_USER != "provision"
