---
- include: iscsi.yml

# Networking
- name: "Remove netplan.io"
  ansible.builtin.apt:
    name: "netplan.io"
    state: "absent"
  tags:
    - "networking"
- name: "Remove netplan directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "/etc/netplan"
    - "/lib/netplan"
    - "/run/netplan"
  tags:
    - "networking"
- name: "Install Dependencies for /etc/network/interfaces"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "latest"
  loop:
    - "ifupdown"
    - "net-tools"
  tags:
    - "networking"
- name: "Setup /etc/network/interfaces"
  ansible.builtin.template:
    dest: "/etc/network/interfaces"
    group: "root"
    mode: "u=rw,g=r,o=r"
    owner: "root"
    src: "network-interfaces.j2"
    validate: "ifup --no-act %s"
  notify: "restart networking interfaces"
  tags:
    - "networking"
- name: "Ensure networking is enabled and unmasked"
  ansible.builtin.systemd:
    enabled: yes
    masked: no
    name: "networking"
  tags:
    - "networking"

- name: "Ensure systemd-networkd[.socket] is stopped and disabled"
  ansible.builtin.systemd:
    enabled: no
    name: "{{ item }}"
    state: "stopped"
  loop:
    - "systemd-networkd"
    - "systemd-networkd.socket"
  tags:
    - "networking"

- name: "Disable systemd-resolved DNS Stub Listener"
  notify: "restart systemd-resolved"
  ansible.builtin.lineinfile:
    insertafter: "[Resolve]"
    line: "DNSStubListener=no"
    path: "/etc/systemd/resolved.conf"
  tags:
    - "networking"
- name: "Setup /etc/resolv.conf"
  ansible.builtin.template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    mode: "u=rw,g=r,o=r"
    owner: "root"
    group: "root"
  tags:
    - "networking"

# Time Management
- name: Set timezone to US/Pacific
  community.general.timezone:
    name: US/Pacific
  become: yes
  become_method: sudo
- name: Ensure chrony is installed
  ansible.builtin.apt:
    name: "chrony"
    state: "latest"
- name: Setup chrony conf
  ansible.builtin.template:
    src: "chrony.conf.ubuntu.j2"
    dest: "/etc/chrony/chrony.conf"
    mode: "u=rw,g=r,o=r"
    owner: "root"
    group: "root"
  register: chrony_conf
- name: Ensure chrony is running with latest config
  ansible.builtin.systemd:
    name: "chrony"
    state: "{% if chrony_conf.changed %}restarted{% else %}started{% endif %}"
    enabled: yes

# Provisoning Cleanup
- name: Remove ubuntu user
  user:
    name: ubuntu
    state: absent
    remove: yes
  when: ansible_distribution == "Ubuntu"

# Zabbix Agent
- name: "Install Zabbix agent repo"
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu{{ ansible_lsb.release }}_all.deb"
  tags:
    - "zabbix-agent"
- name: "Disable zabbix-agent"
  ansible.builtin.systemd:
    name: "zabbix-agent"
    enabled: no
    state: "stopped"
  tags:
    - "zabbix-agent"
- name: "Remove zabbix-agent"
  ansible.builtin.apt:
    name: "zabbix-agent"
    state: "latest"
  tags:
    - "zabbix-agent"
- name: "Install zabbix-agent2"
  ansible.builtin.apt:
    name: "zabbix-agent2"
    state: "latest"
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - "zabbix-agent"
- name: "Remove zabbix-agent files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "/etc/zabbix/zabbix_agentd.conf"
    - "/etc/zabbix/zabbix_agentd.d"
    - "/var/log/zabbix/zabbix_agentd.log"
  tags:
    - "zabbix-agent"
- name: "Enable zabbix-agent2"
  ansible.builtin.systemd:
    name: "zabbix-agent2"
    enabled: yes
  tags:
    - "zabbix-agent"
- name: "Set zabbix-agent Hostname"
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agent2.conf"
    regexp: "^Hostname="
    line: "Hostname={{ inventory_hostname }}"
  notify: "restart zabbix-agent2"
  tags:
    - "zabbix-agent"
- name: "Set zabbix-agent2 Server"
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agent2.conf"
    regexp: "^Server="
    line: "Server=zabbix-server.hogs.tswn.us"
  notify: "restart zabbix-agent2"
  tags:
    - "zabbix-agent"
- name: "Set zabbix-agent2 ServerActive"
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agent2.conf"
    regexp: "^ServerActive="
    line: "ServerActive=zabbix-server.hogs.tswn.us"
  notify: "restart zabbix-agent2"
  tags:
    - "zabbix-agent"
- name: "Ensure zabbix-agent2 is started"
  ansible.builtin.systemd:
    name: "zabbix-agent2"
    state: "started"
  tags:
    - "zabbix-agent"
