---
- include: iscsi.yml

# Networking
- name: Check for existing configurations in /etc/netplan
  ansible.builtin.find:
    recurse: no
    file_type: "file"
    paths:
      - "/etc/netplan"
    excludes:
      - "00-ansible-config.yaml"
    patterns:
      - "*.yaml"
  register: existing_configs
- name: Set aside existing configurations in /etc/netplan
  ansible.builtin.command:
    argv:
      - "mv"
      - "{{ item.path }}"
      - "{{ item.path }}.old"
  loop: "{{ existing_configs.files }}"
  when: existing_configs.matched
- name: Setup networking
  ansible.builtin.template:
    dest: "/etc/netplan/00-ansible-config.yaml"
    group: "root"
    mode: "u=rw,g=r,o=r"
    owner: "root"
    src: "netplan.yaml.j2"
    validate: "netplan try --config-file=%s --timeout=5"
  notify: "netplan apply"

- name: "Disable systemd-resolved DNS Stub Listener"
  notify: "restart systemd-resolved"
  ansible.builtin.lineinfile:
    insertafter: "[Resolve]"
    line: "DNSStubListener=no"
    path: "/etc/systemd/resolved.conf"
- name: "Setup /etc/resolv.conf"
  ansible.builtin.template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    mode: "u=rw,g=r,o=r"
    owner: "root"
    group: "root"

# Time Management
- name: Set timezone to US/Pacific
  community.general.timezone:
    name: US/Pacific
  become: yes
  become_method: sudo
- name: Ensure chrony is installed
  ansible.builtin.apt:
    name: "chrony"
    state: "latest"
- name: Setup chrony conf
  ansible.builtin.template:
    src: "chrony.conf.ubuntu.j2"
    dest: "/etc/chrony/chrony.conf"
    mode: "u=rw,g=r,o=r"
    owner: "root"
    group: "root"
  register: chrony_conf
- name: Ensure chrony is running with latest config
  ansible.builtin.systemd:
    name: "chrony"
    state: "{% if chrony_conf.changed %}restarted{% else %}started{% endif %}"
    enabled: yes

# Provisoning Cleanup
- name: Remove ubuntu user
  user:
    name: ubuntu
    state: absent
    remove: yes
  when: ansible_distribution == "Ubuntu"

# Zabbix Agent
- name: "Install Zabbix agent repo"
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu{{ ansible_lsb.release }}_all.deb"
  tags:
    - "zabbix-agent"
- name: "Install zabbix-agent"
  ansible.builtin.apt:
    name: "zabbix-agent"
    state: "latest"
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - "zabbix-agent"
- name: "Enable zabbix-agent"
  ansible.builtin.systemd:
    name: "zabbix-agent"
    enabled: yes
  tags:
    - "zabbix-agent"
- name: "Set zabbix-agent Hostname"
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agentd.conf"
    regexp: "^Hostname="
    line: "Hostname={{ inventory_hostname }}"
  notify: "restart zabbix-agent"
  tags:
    - "zabbix-agent"
- name: "Set zabbix-agent Server"
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agentd.conf"
    regexp: "^Server="
    line: "Server=zabbix-server.hogs.tswn.us"
  notify: "restart zabbix-agent"
  tags:
    - "zabbix-agent"
- name: "Set zabbix-agent ServerActive"
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agentd.conf"
    regexp: "^ServerActive="
    line: "ServerActive=zabbix-server.hogs.tswn.us"
  notify: "restart zabbix-agent"
  tags:
    - "zabbix-agent"
- name: "Ensure zabbix-agent is started"
  ansible.builtin.systemd:
    name: "zabbix-agent"
    state: "started"
  tags:
    - "zabbix-agent"
