---
ansible_cron__interval: "daily"

common__additional_ethernet_interfaces:
  - name: "eth1"
    inet:
      mode: "manual"
      lines: []

common__gateway_v4_address: "10.10.0.1"
common__ip_addresses:
  - "10.10.0.60/24"
common__nameservers:
  addresses:
    - "10.10.0.1"

common_rpi__cm4io_fan:
  minrpm: 1200
  maxrpm: 5000
common_rpi__cpu_i2c: yes
common_rpi__i2c_rtc: "pcf85063a,i2c_csi_dsi"
common_rpi__overclock: yes
