---
ansible_cron__interval: "daily"

common__additional_ethernet_interfaces:
  - name: "eth1"
    inet:
      mode: "manual"
      lines: []

common__gateway_v4_address: "10.10.0.1"
common__ip_addresses:
  - "10.10.0.60/24"
common__nameservers:
  addresses:
    - "10.10.0.1"

common__pi_usercfg:
  - "# Disable audio"
  - "dtparam=audio=off"
  - "# Enable USB"
  - "dtoverlay=dwc2,dr_mode=host"
  - "# Use the CPU to access i2c"
  - "dtparam=i2c_vc=on"
  - "# RTC"
  - "dtoverlay=i2c-rtc,pcf85063a,i2c_csi_dsi"
  - "# Overclock"
  - "over_voltage=6"
  - "arm_freq=2000"
