---
# tasks file for zabbix
- name: "Create zabbix directory"
  ansible.builtin.file:
    path: "/var/lib/zabbix"
    state: "directory"
    owner: "zabbix"
    group: "zabbix"
    mode: "u=rwx"

- name: "Launch zabbix server and frontend containers"
  community.docker.docker_compose:
    project_name: "zabbix"
    definition:
      services:
        server:
          dns: "{{ common__nameservers.addresses }}"
          environment:
            DB_SERVER_HOST: "mysql.hogs.tswn.us"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: "{{ hostvars['mysql.hogs.tswn.us'].mysql_server__users | selectattr('name', 'equalto', 'zabbix') | map(attribute='password') | first }}"
          image: "zabbix/zabbix-server-mysql:ubuntu-5.4-latest"
          mac_address: "02:42:0a:75:00:20"
          networks:
            home:
              ipv4_address: "10.117.0.32"
              ipv6_address: "fd36:3eb3:43b0:75::20"
              # This also gets an ipv6 address of fd36:3eb3:43b0:75:42:aff:fe75:20, based on the mac address.
          ports:
            - "10051:10051"
          volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "/var/lib/zabbix:/var/lib/zabbix"
        frontend:
          depends_on:
            - "server"
          dns: "{{ common__nameservers.addresses }}"
          environment:
            DB_SERVER_HOST: "mysql.hogs.tswn.us"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: "{{ hostvars['mysql.hogs.tswn.us'].mysql_server__users | selectattr('name', 'equalto', 'zabbix') | map(attribute='password') | first }}"
            ZBX_SERVER_HOST: "zabbix-server.hogs.tswn.us"
            PHP_TZ: "America/Los_Angeles"
            ZBX_DEBUGLEVEL: "5"
          healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/"]
            interval: "10s"
            timeout: "5s"
            retries: 3
            start_period: "30s"
          image: "zabbix/zabbix-web-apache-mysql:ubuntu-5.4-latest"
          mac_address: "02:42:0a:75:00:21"
          networks:
            home:
              ipv4_address: "10.117.0.33"
              ipv6_address: "fd36:3eb3:43b0:75::21"
              # This also gets an ipv6 address of fd36:3eb3:43b0:75:42:aff:fe75:21, based on the mac address.
          ports:
            - "80:8080/tcp"
          volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
      networks:
        home:
          external:
            name: "home"
    pull: yes
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  register: status
- ansible.builtin.assert:
    that:
      - "status.services.server.zabbix_server_1.state.running"
      - "status.services.frontend.zabbix_frontend_1.state.running"