---
# Tasks to configure ansible-agent.
- name: "Ensure /var/log/zabbix exists with the correct permissions"
  ansible.builtin.file:
    group: "zabbix"
    mode: "u=rwx,g=rx,o=rx"
    owner: "zabbix"
    path: "/var/log/zabbix"
    state: "directory"
- name: "Ensure /var/run/zabbix exists"
  ansible.builtin.file:
    group: "zabbix"
    mode: "u=rwx,g=rx,o=rx"
    owner: "zabbix"
    path: "/var/run/zabbix"
    state: "directory"
- name: "Setup zabbix-agent configuration file"
  ansible.builtin.template:
    dest: "{{ common__etc_dir }}/zabbix/zabbix_agentd.conf"
    owner: "root"
    group: "{% if ansible_distribution == 'FreeBSD' %}wheel{% else %}root{% endif %}"
    mode: "u=rw,g=r,o=r"
    src: "zabbix-agentd.conf.j2"
  notify: "restart zabbix-agent"
