---
# Handle old zabbix-agent installs
- name: "Remove old zabbix-agent config"
  ansible.builtin.file:
    path: "{{ common__etc_dir }}/zabbix/zabbix_agentd.conf"
    state: "absent"
  tags:
    - "zabbix-agent"

# Tasks to configure ansible-agent2.
- name: "Set zabbix-agent2 Hostname"
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agent2.conf"
    regexp: "^Hostname="
    line: "Hostname={{ inventory_hostname }}"
  notify: "restart zabbix-agent"
  tags:
    - "zabbix-agent"
- name: "Set zabbix-agent2 Server"
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agent2.conf"
    regexp: "^Server="
    line: "Server=server.zabbix.hogs.tswn.us"
  notify: "restart zabbix-agent"
  tags:
    - "zabbix-agent"
- name: "Set zabbix-agent2 ServerActive"
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agent2.conf"
    regexp: "^ServerActive="
    line: "ServerActive=server.zabbix.hogs.tswn.us"
  notify: "restart zabbix-agent"
  tags:
    - "zabbix-agent"
