---
# Tasks to configure ansible-agent.
- name: "Ensure Zabbix paths exist with the correct permissions"
  ansible.builtin.file:
    group: "zabbix"
    mode: "u=rwx,g=rx,o=rx"
    owner: "zabbix"
    path: "{{ item }}"
    recurse: yes
    state: "directory"
  loop:
    - "/var/run/zabbix"
    - "/var/log/zabbix"
  tags:
    - "zabbix-agent"
- name: "Ensure /etc/zabbix/zabbix_agent.d/ exists with the correct permissions"
  ansible.builtin.file:
    group: "{% if ansible_distribution == 'FreeBSD' %}wheel{% else %}root{% endif %}"
    mode: "u=rwx,g=rx,o=rx"
    owner: "zabbix"
    path: "{{ common__etc_dir }}/zabbix/zabbix_agent.d/"
    recurse: yes
    state: "directory"
  tags:
    - "zabbix-agent"
- name: "Setup zabbix-agent configuration file"
  ansible.builtin.template:
    dest: "{{ common__etc_dir }}/zabbix/zabbix_agentd.conf"
    owner: "root"
    group: "{% if ansible_distribution == 'FreeBSD' %}wheel{% else %}root{% endif %}"
    mode: "u=rw,g=r,o=r"
    src: "zabbix-agentd.conf.j2"
  notify: "restart zabbix-agent"
  tags:
    - "zabbix-agent"
