---
# Tasks for zabbix-agent installation and configuration.
- ansible.builtin.import_tasks: "freebsd.yml" # zabbix-agent
  when: "ansible_distribution == 'FreeBSD'"
- name: "Install Zabbix Repository"
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu{{ ansible_lsb.release }}_all.deb"
  when: "ansible_distribution == 'Ubuntu'"
- ansible.builtin.import_tasks: "ubuntu2.yml" # zabbix-agent2
  when: "ansible_distribution == 'Ubuntu' and ansible_architecture == 'x86_64'"
- ansible.builtin.import_tasks: "ubuntu.yml" # zabbix-agent
  when: "ansible_distribution == 'Ubuntu' and ansible_architecture == 'armv7l'"
