---
# Tasks for zabbix-agent installation and configuration.
- include: "freebsd.yml" # zabbix-agent
  when: "ansible_distribution == 'FreeBSD'"
- name: "Install Zabbix Repository"
  ansible.builtin.apt:
    # Ideally, we would use the ansible_lsb.release here, however Zabbix only supports LTS
    # releases, so we just use the previous package that is available (20.04).
    deb: "https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu20.04_all.deb"
  tags:
    - "zabbix-agent"
  when: "ansible_distribution == 'Ubuntu'"
- include: "ubuntu2.yml" # zabbix-agent2
  when: "ansible_distribution == 'Ubuntu' and ansible_architecture == 'x86_64'"
- include: "ubuntu.yml" # zabbix-agent
  when: "ansible_distribution == 'Ubuntu' and (ansible_architecture == 'armv7l' or ansible_architecture == 'aarch64')"
